name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup JDK 17 (for Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 3: Setup Gradle Cache (for faster builds)
      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2

      # Step 4: Build the Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 5: Upload the Debug APK as an Artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    if: github.event_name == 'release'
    name: Build and Release APK
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 3: Build the Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Step 4: Upload Release APK to GitHub Releases
      - name: Upload Release APK
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
